// Generated by https://quicktype.io

export interface IReservaCliente {
  total:       number;
  allReservas: Reserva[];
}
export interface IReservaAdmin {
  total:       number;
  allReservas: ReservaAdmin[];
}

export interface Reserva {
  id:            number;
  estado:        boolean;
  fecha_reserva: string;
  libro:         Libro;
}
export interface ReservaAdmin {
  id:            number;
  estado:        boolean;
  fecha_reserva: string;
  libro:         Libro;
  cliente:       {
    id:          number,
    nombre:       string
  };
}

export interface Libro {
  id:     number;
  titulo: string;
  precio: string;
}
export interface IBodyReservaAxios extends IBodyReserva{
  libroId: number
}

export interface IBodyReserva {
  fecha_reserva: string,
}


// Generated by https://quicktype.io

export interface IResponseReserva {
  id:            number;
  estado:        boolean;
  fecha_reserva: string;
  createdAt:     string;
  updatedAt:     string;
  clienteId:     number;
  libroId:       number;
}
