import { IRol } from "./rol"

export interface IListUsers {
  total: number,
  allUsers: Array<IUsers>
}

export interface IUser {
  id: number,
  email: string,
  nombre: string,
  telefono: string,
  password?: string
  rol: {
    descripcion: string
  }| IRol
}

export interface ICreateUser {
  user: User;
}

export interface User {
  id?:        number;
  nombre:    string;
  telefono:  string;
  email:     string;
  password?:  string;
  createdAt?: string;
  updatedAt?: string;
  rolId:     number;
}

export interface IUsers {
  id: number,
  email: string,
  nombre: string,
  telefono: string,
  rol: IRol
}


export interface ICrearUsuario {
  nombre: string,
  email: string,
  telefono: string,
  password: string,
  rolId: number,
}

// Generated by https://quicktype.io

export interface IUserGet {
  user: User;
}

